# 客户端只认 Zookeeper，由 Zookeeper 告诉它真正的 Server 在哪
zookeeper_ip = 127.0.0.1
zookeeper_port = 2181

# 每个 ip:port 队列最多保留 500 个空闲连接
max_idle_per_host = 500
# 每个 ip:port 最多允许同时存在 600 个连接
max_active_per_host = 600
